# Generated by Django 6.0.6 on 2026-06-22 07:45

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('woman', 'woman'), ('man', 'man'), ('unSelected', 'unSelected')], default='unSelected', max_length=100)),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('birth_day', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('last_seen', django_jalali.db.models.jDateTimeField()),
                ('is_online', models.BooleanField(default=False)),
                ('created_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_date', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date', '-updated_date'],
            },
        ),
    ]
