# Generated by Django 6.0.6 on 2026-06-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
